//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class LecturaSensores
    {
        public System.DateTime Fecha_Lectura { get; set; }
        public Nullable<double> Latitud { get; set; }
        public Nullable<double> Longitud { get; set; }
        public Nullable<int> Velocidad { get; set; }
        public Nullable<double> Aceleracion { get; set; }
        public Nullable<double> Temperatura { get; set; }
        public Nullable<double> Presion { get; set; }
        public Nullable<int> Nivel_Combustible { get; set; }
        public Nullable<bool> Alarma_Activa { get; set; }
        public Nullable<int> Id_Sensor { get; set; }
        public int Id { get; set; }
    
        public virtual Sensores Sensores { get; set; }
    }
}
